use customelement instead of having main.js
[Notes]
- adding dist folder
- in dev mode, put built JS files in public dir to avoid symlink

[Bug] comment out uglify plugin, for now; error message:
```
    src/main.js → dist/custom.js...
    [!] (uglify plugin) Error: Error transforming bundle with 'uglify' plugin: Unexpected token: punc (,)
    Error: Error transforming bundle with 'uglify' plugin: Unexpected token: punc (,)
        at error (/usr/local/lib/node_modules/rollup/dist/rollup.js:224:15)
        at /usr/local/lib/node_modules/rollup/dist/rollup.js:17985:17
        at <anonymous>
```